name: build-app
run-name: build app from the ${{ github.head_ref }} branch
on: pull_request
jobs:
  build-woof-target:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Xcode 14.3
        run: sudo xcode-select --switch /Applications/Xcode_14.3.app
      - name: Build iOS Simulator
        run: ./scripts/build-ios-simulator.sh
