name: build-and-test
run-name: build app from the ${{ github.head_ref }} branch
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "15 4,5 * * *"

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
  build-woof-target:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Swift dependencies
        uses: actions/cache@v4
        with:
         path: ~/.swiftpm
         key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}

      - name: Install xcpretty
        run: |
         gem install xcpretty
         echo 'export PATH="$(gem environment gemdir)/bin:$PATH"' >> ~/.bash_profile

      - name: Build iOS Simulator
        run: ./scripts/build-ios-simulator.sh

      - name: Run tests
        run: ./scripts/run-unit-tests.sh

      - name: Run formater
        run: |
         swiftformat --lint . \
         --config .swiftformat \
         --quiet
#
#      - name: Run linter
#        run: |
#         swiftlint --config .swiftlint.yml \
#         --strict \
#         --quiet
