name: build-and-test
run-name: build app from the ${{ github.head_ref }} branch
on: pull_request
jobs:
  build-woof-target:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build iOS Simulator
        run: ./scripts/build-ios-simulator.sh
      - name: Run tests
        run: ./scripts/run-unit-tests.sh
