name: build-app
run-name: build app from the ${{ github.head_ref }} branch
on: pull_request
jobs:
  build-woof-target:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8.0"
      - name: Build iOS Simulator
        run: ./scripts/build-ios-simulator.sh
